apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mykuardapp
  namespace: argocd
spec:
  project: endor
  source:
    repoURL: https://github.com/crisboot/akuity-gitops-masterclass-app
    targetRevision: main
    path: impersonation/manifests/
  destination:
    namespace: kuard
    server: https://kubernetes.default.svc
  syncPolicy: {}
